# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bbb2871f8ec15e3e0256307ee7552364b7c64229524da5e3cc6773738bccf1a5327d2b813b3de250840703503d6d05e2b07974b814b1d163cce4db97df587c43

test:
  secret_key_base: 0248d0a3c32254c55ab0fe17422c9494686506523b9d5c285c3f253736cd67038aacfe7534b54d38492803867130fe5d6e4a99b45260d715795232af6460087d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
